# Generated by Django 4.2.1 on 2023-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interests',
            field=models.ManyToManyField(blank=True, to='matcher.interest'),
        ),
    ]
