# Generated by Django 4.2.1 on 2023-12-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_sent_by_alter_chatroom_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='client',
        ),
    ]
