# Generated by Django 4.2.1 on 2023-12-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountInterest',
        ),
    ]
